[package]
name = "portmate-process-watchdog"
version = "0.1.8"
edition.workspace = true
license.workspace = true
authors.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_System_Threading",
] }
